apiVersion: apps/v1
kind: Deployment
metadata:
  name: batman-deployment
  namespace: webapps
  labels:
    app: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
        version: blue
    spec:
      containers:
        - name: batman-container
          image: prcdocker/batman-web:1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "300Mi"
            limits:
              cpu: "250m"
              memory: "350Mi"
