apiVersion: apps/v1
kind: Deployment
metadata:
  name: batman-deployment
  namespace: webapps
  labels:
    app: Apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Apache
  template:
    metadata:
      labels:
        app: Apache
        version: blue
    spec:
      containers:
        - name: batman-container
          image: prcdocker/superman-web:1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "200m"
              memory: "300Mi"
            limits:
              cpu: "250m"
              memory: "350Mi"
